#!/usr/bin/env bash
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &
bin/console app:demo &