services:
    AppBundle\Doctrine\Annotation\EntityInherit\EntityInheritListener:
        public: true
        autowire: true
        arguments:
            $strict: '%kernel.debug%'
        calls:
            - ['setAnnotationReader', ['@Doctrine\Common\Annotations\Reader']]
        tags:
            - { name: doctrine.orm.entity_listener, lazy: true }

    AppBundle\Doctrine\Annotation\SequencedCode\SequencedCodeGeneratorListener:
        public: true
        autowire: true
        arguments:
            $strict: '%kernel.debug%'
        calls:
            - ['setAnnotationReader', ['@Doctrine\Common\Annotations\Reader']]
        tags:
            - { name: doctrine.orm.entity_listener, lazy: true }

    AppBundle\Doctrine\Annotation\TreePath\TreePathListener:
        public: true
        autowire: true
        arguments:
            $strict: '%kernel.debug%'
        tags:
            - { name: doctrine.orm.entity_listener, lazy: true }