services:
#    AppBundle\Doctrine\Annotation\EntityInherit\EntityInheritListener:
#        public: true
#        autowire: true
#        arguments:
#            $strict: '%kernel.debug%'
#        calls:
#            - ['setAnnotationReader', ['@Doctrine\Common\Annotations\Reader']]
#        tags:
#            - { name: doctrine.orm.entity_listener, lazy: true }
#
#    AppBundle\Doctrine\Annotation\SequencedCode\SequencedCodeGeneratorListener:
#        public: true
#        autowire: true
#        arguments:
#            $strict: '%kernel.debug%'
#        calls:
#            - ['setAnnotationReader', ['@Doctrine\Common\Annotations\Reader']]
#        tags:
#            - { name: doctrine.orm.entity_listener, lazy: true }
#
#    AppBundle\Doctrine\Annotation\TreePath\TreePathListener:
#        public: true
#        autowire: true
#        arguments:
#            $strict: '%kernel.debug%'
#        tags:
#            - { name: doctrine.orm.entity_listener, lazy: true }

    AppBundle\Doctrine\Processor\EntityInherit\EntityInheritProcessor:
        lazy: true
        tags:
            - { name: entity_processor }

    AppBundle\Doctrine\Processor\SequencedCode\SequencedCodeGeneratorProcessor:
        lazy: true
        tags:
            - { name: entity_processor }

    AppBundle\Doctrine\EntityProcessorRegistry:
        arguments:
            $entityProcessors: !tagged entity_processor

    AppBundle\Doctrine\AnnotationConfigurationResolver:
        public: false
        autowire: true

    AppBundle\Doctrine\EntityProcessorOrchestrator:
        public: true
        autowire: true
        arguments:
            $entityClass: AppBundle\Entity\Area
        tags:
            - { name: doctrine.orm.entity_listener, event: preFlush, entity: AppBundle\Entity\Area, lazy: true }