services:
    app.annotation_bind_registry:
        class: \stdClass

    app.annotation_bind.entity_inherit:
        class: \stdClass
    app.annotation_bind.sequenced_code:
        class: \stdClass
    app.annotation_bind.tree_path:
        class: \stdClass

    app.annotation_binder.area:
        class: AppBundle\Doctrine\Annotation\AnnotationBinder\AnnotationBinderSubscriber
        autowire: true
        arguments:
            $class: AppBundle\Entity\Area
            $sequence: ['EntityInherit', 'SequencedCode', 'TreePath']
        tags:
            - { name: doctrine.event_subscriber }